"""Regenerate and verify MANIFEST.sha256 — the release integrity manifest.

The manifest covers every file in the release set — tracked plus untracked
non-ignored files in a worktree, or the manifest's own file list in a
packaged tree that has no ``.git`` — in sorted order, in ``sha256sum``
format (``<hash>  <path>``). The manifest file itself is never listed, and
neither is ``MANIFEST.sig``: the signature block attests to the manifest's
own digest, so listing it would create an unsatisfiable self-reference (the
signature exists only after the manifest's digest is fixed).
``VALIDATION.generated.md`` is likewise excluded — it is regenerated by the
qualification pipeline after the manifest check runs.

    uv run python scripts/update_manifest.py            # regenerate
    uv run python scripts/update_manifest.py --check    # verify, write nothing

``--check`` is the portable equivalent of ``sha256sum -c MANIFEST.sha256``
(which CI runs) for platforms without coreutils: it regenerates the expected
content and compares byte-for-byte, so a stale hash, a missing file, a wrong
path, or a formatting drift all fail the same way. In a packaged tree (no
``.git``) it additionally enumerates the files actually present and fails
on anything the manifest does not list — a signature over the manifest can
only vouch for a fully specified release set.
"""

import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = "MANIFEST.sha256"
# The manifest signature is a release artifact produced by sign_manifest.py
# *after* the manifest is frozen — it can never be a member of the set its
# own signature authenticates. Excluded from every file-set enumeration so
# a signed worktree still passes --check. VALIDATION.generated.md is also
# generated-at-qualification content: the pipeline rewrites it after the
# manifest check runs, so hashing it would make the manifest stale by
# construction. It is a report, not source.
SIG_FILE = "MANIFEST.sig"
GENERATED_REPORT = "VALIDATION.generated.md"
_EXCLUDED = {MANIFEST, SIG_FILE, GENERATED_REPORT}

# Ignore set for packaged-tree enumeration, mirroring .gitignore. It is
# deliberately narrow — runtime detritus only — so an unexpected file added
# to an unpacked release still fails --check instead of hiding here.
_IGNORE_DIRS = {
    ".git", ".venv", "__pycache__", ".pytest_cache", ".ruff_cache",
    ".hypothesis", "artifacts", "dist", ".jev", "mutants", "htmlcov",
    "node_modules",
}
_IGNORE_NAMES = {
    ".env", ".DS_Store", ".coverage", "coverage.xml", "setup.cfg",
}
_IGNORE_SUFFIXES = (".pyc", ".jsonl.lock")


def _packaged_files(root: Path) -> list[str]:
    """Actual regular files on disk in a tree without git metadata.

    The manifest's own list specifies the expected set; this enumeration is
    what lets --check reject files the manifest does not cover."""
    found = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        parts = path.relative_to(root).as_posix().split("/")
        if any(part in _IGNORE_DIRS or part.endswith(".egg-info") for part in parts[:-1]):
            continue
        name = parts[-1]
        if name in _IGNORE_NAMES or name in _EXCLUDED or name.endswith(_IGNORE_SUFFIXES):
            continue
        found.append("/".join(parts))
    return sorted(found)


def _tracked_files(root: Path) -> tuple[list[str], bool]:
    """The manifest's file set: tracked *and* untracked non-ignored files in a
    worktree (a not-yet-staged release file must not be silently dropped),
    else the existing manifest's own list — a packaged tree has no .git and
    that list is still the authoritative release set.

    Returns ``(files, from_git)``: ``from_git`` is False in packaged mode,
    where --check additionally compares the manifest list against the files
    actually present so unlisted extras fail closed."""
    try:
        out = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
            cwd=root, capture_output=True, text=True, check=True,
        ).stdout
        files = [name for name in out.splitlines() if name.strip()]
    except (OSError, subprocess.CalledProcessError):
        files = []
    if files:
        # .gitignore keeps the signature out of the normal enumeration, but a
        # force-added MANIFEST.sig would ship tracked yet uncovered — fail
        # closed rather than silently dropping it from the file set.
        tracked_sig = subprocess.run(
            ["git", "ls-files", "--error-unmatch", "--", SIG_FILE],
            cwd=root, capture_output=True,
        )
        if tracked_sig.returncode == 0:
            raise SystemExit(
                f"{SIG_FILE} is tracked by git — it must never enter the "
                "release set it authenticates (git rm --cached it)"
            )
        return sorted(name for name in files if name not in _EXCLUDED), True
    manifest = root / MANIFEST
    if not manifest.exists():
        raise SystemExit(
            "no git worktree and no MANIFEST.sha256 to re-cover; "
            "nothing to regenerate from"
        )
    files = [
        line.split("  ", 1)[-1].strip()
        for line in manifest.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    return sorted(name for name in files if name not in _EXCLUDED), False


def _render(root: Path, files: list[str]) -> str:
    lines = []
    for name in files:
        digest = hashlib.sha256((root / name).read_bytes()).hexdigest()
        lines.append(f"{digest}  {name}")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    files, from_git = _tracked_files(ROOT)
    try:
        expected = _render(ROOT, files)
    except OSError as exc:
        print(f"{MANIFEST}: listed file unreadable: {exc}", file=sys.stderr)
        return 1
    manifest = ROOT / MANIFEST
    if not check:
        manifest.write_text(expected, encoding="utf-8")
        print(f"{MANIFEST}: regenerated over {len(files)} files")
        return 0
    actual = manifest.read_text(encoding="utf-8") if manifest.exists() else ""
    if actual == expected:
        if not from_git:
            # In a packaged tree the manifest's own list was the spec —
            # digest equality alone cannot detect files added after
            # unpacking. Enumerate what is actually there and fail on
            # anything the manifest does not cover.
            extra = sorted(set(_packaged_files(ROOT)) - set(files))
            if extra:
                print(
                    f"{MANIFEST}: {len(extra)} file(s) present but not listed:",
                    file=sys.stderr,
                )
                for name in extra:
                    print(f"  unexpected: {name}", file=sys.stderr)
                return 1
        print(f"{MANIFEST}: {len(files)} entries verified")
        return 0
    expected_lines = expected.splitlines()
    actual_lines = actual.splitlines()
    for i, want in enumerate(expected_lines):
        got = actual_lines[i] if i < len(actual_lines) else "<missing>"
        if got != want:
            print(f"{MANIFEST}: first mismatch at line {i + 1}:", file=sys.stderr)
            print(f"  expected: {want}", file=sys.stderr)
            print(f"  actual:   {got}", file=sys.stderr)
            break
    else:
        print(
            f"{MANIFEST}: {len(actual_lines)} entries vs {len(expected_lines)} expected",
            file=sys.stderr,
        )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
